### ISSUE TITLE
Lack of mapping when querying for documents

### ISSUE THREAD

**Issue by ghost** [PHPholics/MongoDbBundle#1]
Hello,

Let's say I have such document:
```
class MyDocument extends Document
{
    /**
     * @ES\Property(type="date")
     * @Mongo\Property(name="occurrence_date", type="datetime")
     */
    protected $occurrenceDate;
}
```

`Collection::findOne` doesn't map PHP class property (`occurrenceDate`) name to it's representation in MongoDb document (`occurrence_date`). This means that this query:
```
$collection->findOne(['occurenceDate' => '2018-01-25T00:00:00+00:00'])
```
should result in this query in Mongo Shell:
```
db.getCollection('my_document').findOne({'occurence_date': '2018-01-25T00:00:00+00:00'})
```

**Comment by kwojc** [comment]
Done 

https://github.com/PHPholics/MongoDbBundle/commit/c0e08af5bac37555d22e30f7eb176502338bf6ee
